# check default values file
# https://github.com/traefik/traefik-helm-chart/blob/v10.24.0/traefik/values.yaml
service:
  type: NodePort
  #type: LoadBalancer
ports:
  traefik:
    port: 9000
    expose: true
    exposedPort: 9000
    nodePort: 32090 # has to match http container port of the cluster config KIND_NODE_PORT_TRAEFIK
  web:
    port: 8000
    expose: true
    exposedPort: 8000
    protocol: TCP
    nodePort: 32080 # has to match http container port of the cluster config KIND_NODE_PORT_HTTP
  websecure:
    port: 8443
    expose: true
    protocol: TCP
    exposedPort: 443
    nodePort: 32443 # has to match https container port of the cluster config KIND_NODE_PORT_HTTPS
    tls:
      enabled: true
#volumes:
#  - name: traefik
#    mountPath: "/etc/traefik/"
#    type: configMap
#additionalArguments:
#  - --providers.file.filename=/etc/traefik/traefik.yaml
nodeSelector:
  ingress-ready: 'true' # assign to the kind-control-plane
#tolerations:
#  - key: node-role.kubernetes.io/master
#    operator: Equal
#    effect: NoSchedule
ingressRoute:
  dashboard:
    enabled: true

# Logs
# https://docs.traefik.io/observability/logs/
logs:
  # Traefik logs concern everything that happens to Traefik itself (startup, configuration, events, shutdown, and so on).
  general:
    # By default, the logs use a text format (common), but you can
    # also ask for the json format in the format option
    # format: json
    # By default, the level is set to ERROR. Alternative logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
    level: INFO
  access:
    # To enable access logs
    enabled: true